### ISSUE TITLE
List of tutorials that we need to add

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy_notebooks#32]
There are several tutorials that we need to add: @giovp 

first, we would like to have a tutorial for analysing each of the different datasets using Squidpy functions:
- [x] visium h&e (see #12)
- [x] visium fluo (see #9)
- [x] seqfish (see #12)
- [x] imc (see #12)
- [x] 4i (see #12)

then, there are tutorial showing additional functionality using external methods. These tutorials should most likely be excluded from CI as they use external packages and could take long to run. We could also put them in a separate heading, like "external" (and the other tutorials could be "squidpy core" or sth like that)
- [x] applying DL on top of squidpy (use images & cluster labels to train resnet) (see #12) - Giovanni
- [x] using DL to extract features (needs some additional code in squidpy) (see #35) - Hannah
- [x] using DL to segment cells (need to find a good model to do that first) - Hannah
- [x] joint clustering of image features and gene expression - Giovanni
- [x] deconvolution - Giovanni

**Comment by hspitzer** [comment]
all done!
