### ISSUE TITLE
new notebooks / examples

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy_notebooks#62]
Here a list of examples / notebooks for new functions that we need add @giovp :
## To update
- [x] update ImageContainer example (setting layers with img['layer'], and changes introduced by https://github.com/theislab/squidpy/pull/324 ) -> #64 
- [x] update processing example with Dask image changes -> #64
- [x] update feature extraction examples
- [x] update segmentation example with pointers to how borders between chunks are handled. Also update image tutorials with this
- [x] building a spatial graph with new functionalities
- [ ] update Napari tutorial with pointers to z-stack functionalities (low prio) @giovp 
- [x] update visium tutorials

## New examples
- [x] add an example for img.show which now has some nice functionalities @giovp 
- [x] add example for sq.pl.extract @giovp 
- [x] example showing how to chain cropping and scaling functions (dummy data) -> in image container overview tutorial #64
- [x] examples for new spatial stats (ripleys, moran/geary and sepal)
- [x] example for using apply function with custom functions @dineshpalli  -> in new pr
- [x] example for using spot generator for custom feature extraction workflows @dineshpalli  -> in new pr
- [x] example of `img.subset` -> in compute_crops.py #64 

## New tutorials
- [x] one tutorial analysis for each dataset
- [x] tutorial on using and visualising zstacks (with feature extraction)
- [x] tutorial on plot graph stats on 3D data
- [x] external tutorial for cell-segmentation with stardist
- [x] external tutorial for cell segmentation with cellpose
- [x] external tutorial for image features with cell profiler -> #63

**Comment by giovp** [comment]
hey, sorry just saw this, really nice, added couple of more.
Here's some comments:

> example showing how to chain cropping and scaling functions (dummy data)

this to me is key, needs to be really clear how cropping/uncropping/subset works

> tutorial on plot graph stats on 3D data

good reminder

> one tutorial analysis for each dataset

Yes? boring/tedious but I guess we can't really escape it.

**Comment by giovp** [comment]
>  add an example for img.show which now has some nice functionalities @giovp

shall I use mibitof instead of fluorescent crop data? cause the latter I can only show different channels etc. and not segmentation masks, not sure how interesting...

**Comment by hspitzer** [comment]
> > add an example for img.show which now has some nice functionalities @giovp
> 
> shall I use mibitof instead of fluorescent crop data? cause the latter I can only show different channels etc. and not segmentation masks, not sure how interesting...

Yes, good idea! We were going to use diverse data in the examples / tutorials anyways. Have a look at my mibitof tutorial in #64  to see how I concatenate the images in the image container.

**Comment by michalk8** [comment]
@giovp @hspitzer think this can be also closed, or?

**Comment by giovp** [comment]
I think @hspitzer has still some examples in mind but I don't think we'll include it in this relase.

**Comment by hspitzer** [comment]
correct, there are still 2 open TODOs, we can open a new issue for this, or keep this open until I have time to make the examples. They don't need to be included in the release though.

**Comment by giovp** [comment]
@dineshpalli as discussed:
- function to show example for: https://squidpy.readthedocs.io/en/latest/classes/squidpy.im.ImageContainer.apply.html
- example to use as backbone: https://squidpy.readthedocs.io/en/latest/auto_examples/image/compute_gray.html and not rendered: https://github.com/theislab/squidpy_notebooks/blob/master/examples/image/compute_gray.py

You can check out contributing guides in the link I sent you and you should be good to go. Feel free to reach out for anything, Giovanni
